### ISSUE TITLE
Having trouble understanding what nufft type 1 is doing

### ISSUE THREAD

**Issue by erny123** [ludvigak/FINUFFT.jl#50]
I'm trying to learn some basic Non-Uniform FFT.

I want to see if I can get a frequency spectrum of a laser pulse with a NUFFT type 1 using the FINUFFT.jl library. 

Here's the example:

```
using FFTW
using FINUFFT

c = 2.998e8; #m/s speed of light
wl = 525.0e-9; #m wavelength

fwhm = 500.0e-15; #temporal fwhm
tau0 = fwhm/sqrt(2*log(2)); #gaussian fwhm
tlbw = 0.44/fwhm #transform limited bandwidth
	
maxf = c/wl +tlbw
minf = c/wl-tlbw
df = (maxf - minf)/1.0e3
	
	
#simulation
dt = pl/5.0;
t0 = -2.0*fwhm
tend = 2.0*fwhm
ttot = ceil(Int64,(tend-t0)/dt)

E = [exp(-t^2/tau0^2)*cos(2.0*pi*wlfreq*t) for t in t0:dt:tend];
t = [i for i in t0:dt:tend];
lent = length(E)
Nt = length(t);
```

The pulse looks like: 

![6b1421465e596c6796cb01e0c6a6616b6df4e55f](https://github.com/ludvigak/FINUFFT.jl/assets/34816295/ce907010-277e-4d94-8263-75f28bd45f5f)

Taking the fft:

```

freq = FFTW.fftshift(FFTW.fftfreq(lent,1/dt))
Ef = FFTW.fftshift(FFTW.fft(E));
If = abs2.(Ef); #intensity spectrum
```

Looks like:

![322f0939a12b017aeee34d3be2fbe405cb7768d7](https://github.com/ludvigak/FINUFFT.jl/assets/34816295/2b18781d-774d-44c0-af65-9ef8538eba8b)

Which is exactly what I expect. 

Now I want to us a NUFFT type 1 according to: 
[https://finufft.readthedocs.io/en/latest/math.html](https://finufft.readthedocs.io/en/latest/math.html)

I decide to take nonuniform points in the form of a tangent curve so as to get most of the FWHM of the pulse:

```
#nonuniform indices to extract sampling points
#using tangent curve
maxpi = pi*22.0/100.0;
dpi = 2.0*maxpi/(lent/2);
l = [i for i in -maxpi:dpi:maxpi];
tt = @. tan(1.95*l);
ttt = @. -tt[1]+tt;
ttt = @. ttt*lent/8.81+1;
t4 = @. ceil(Int64,ttt);

#extract nonuniform points
Enu = convert.(ComplexF64,E[t4]); #field at nonuniform points
tnu = t[t4]; #time at noniniform points
lentnu = length(Enu)
```

This looks like:
![4d7cc62791279e55ffd292eaea7e9e0d4129a903](https://github.com/ludvigak/FINUFFT.jl/assets/34816295/0a0e0ec5-e9af-4f3e-bfab-cdbe3199f37a)

```
wmax = freq[end]; #max freq get from previous FFTW, around 1.5e15
Nw = length(freq); #number of total points|
dw = 2*wmax/Nw; # spacing of target k grid|
w = dw .* [i for i in ceil(Int64,-Nw/2):ceil(Int64,Nw/2-1)]; #    % a particular uniform M-grid of this spacing|
#normalize
Enunorm = Enu ./ maximum(E)

fhat = FINUFFT.nufft1d1(tnu, Enunorm, 1, 1.0e-12, Nw);   #% type 1, requesting M modes
```

And the intensity spectrum looks like:
![8f951a942f060885bb7b455bd1c1064d83c54b7a](https://github.com/ludvigak/FINUFFT.jl/assets/34816295/7554cc50-7df2-4016-8d7c-adc15e66e121)

Not sure what to make of it. The amplitudes change but by an extremely small bit? 
The main pulse frequency is off by more than 2.

**Comment by ahbarnett** [comment]
Dear erny,
It is quite hard to understand your example, I'm afraid, and my PhD is in physics.
Partly because the code doesn't run (`pl`, `wlfreq` not defined).
Why are you trying to use NUFFT? Is the FFT not adequate? Why do you want to sparsify your data?

Many suggestions:
* Give a minimally-complete example of your problem. This makes it more likely someone can understand it.
* work in nondimensionalized units so numbers are O(1) not O(1e-15). General good practice.
* first test NUFFT in the uniform case, to make sure you understand its definition relative to the DFT (=FFT).
* your code for the NU pts `t4` is confusing. Let's say I guess `tlen` is 1e5. Then I see `t4` is a grid with higher density in the middle. 
* There are two ways to estimate spectra from data on NU pts:

  1) get a quadrature scheme for your NU pts t_j, meaning a set of numbers w_j such that
    \sum_{j=1}^M f(t_j) w_j   \approx   \int_a^b  f(t) dt

  You then send in w_j f_j to the type-1, not merely f_j your plain samples.
   Eg see: https://finufft.readthedocs.io/en/latest/tutorial/contft.html#d-fts-evaluated-at-arbitrary-frequencies
  You could do a crude estimate of w_j = (t_{j+1}-t_{j-1}) / 2     for a smoothly NU grid.
   But because you do some weird integer quantization subsampling, that may not be good.

  2) invert the type-2 NUFFT. This solves a linear system to get the c_j coeffs, using CG on the normal eqns. I don't have a tutorial example yet.

Good luck, Alex

**Comment by erny123** [comment]
@ahbarnett 
Sorry for the incomplete example. Since it's difficult to plot in Julia I've been having to go back and forth between python and julia trying to find good ways to visualize.
However, looks like pluto notebooks are a good compromise although still much slower than python for basic plotting. 

So I've attached the notebook here and the pdf. 
I highly suggest you put in an example like this: a basic laser pulse in time. 
A lot of upfront examples in the docs aren't really  helpful because it's just random junk and for those of us that are new to NUFFT terminology, it's difficult to distinguish when examples use "nonuniform samples" to mean time/space points or frequency points. 

For the most part I figured it out, I needed more resolution (according to t he nyquist). 


Currently I am working on making some algorithms using the split step FFT method. 
I'm interested in the NUFFT to cut computation cost because the nonlinear operator is only nonzero in a certain range of the frequency spectrum. 

1. The important part for me would be getting a uniform samples in time --> NUFFT to the frequency range that is important  
2. multiplying nonuniform spectrum by a nonlinear operator
3. ---> Inverse NUFFT back to uniform sample in time

However, some things concern me: 

- The nonuniform sampling to uniform frequency spectra (type 1) does not seem to have similar values of the real or imaginary parts as a regular DFT. 
- How to take the inverse nufft. In the example, I try to do the type 1 transform back to uniform time domain which comes out very close but no exact. 


[NUFFT.pdf](https://github.com/ludvigak/FINUFFT.jl/files/12643798/NUFFT.pdf)

**Comment by ludvigak** [comment]
Hi, 
I haven't read through your post properly so apologies if I'm a bit off here. When trying to figure things like this out I usually find it helpful to compute the non-uniform Fourier transform through the direct sum rather than through FINUFFT. You can find examples of the direct sums in the unit tests:
https://github.com/ludvigak/FINUFFT.jl/blob/master/test/test_nufft.jl
That way, you can figure out if the problem is in your formulation or in how you interface to the library.

**Comment by erny123** [comment]
Got it. You are not way off at all and I appreciate any advice to learning NUFFT. I'll look into the direct sum. 

If this turns out to be a good example of solving a basic partial differential equation wave problem (specifically for beam propagation with nonlinear interactions), I would be more than happy to iron out a tutorial for others to use.
